#!/bin/bash
mkdir ~/.vim-plugins
cd ~/.vim-plugins

# Download vim plugins
git clone https://github.com/tpope/vim-pathogen
git clone https://github.com/scrooloose/nerdcommenter
git clone https://github.com/scrooloose/nerdtree
git clone https://github.com/vim-scripts/taglist.vim
git clone https://github.com/altercation/vim-colors-solarized
